# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setWindowModality(QtCore.Qt.NonModal)
        LoginWindow.resize(370, 292)
        self.name_label = QtWidgets.QLabel(LoginWindow)
        self.name_label.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.name_label.setObjectName("name_label")
        self.code_label = QtWidgets.QLabel(LoginWindow)
        self.code_label.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.code_label.setObjectName("code_label")
        self.code_line = QtWidgets.QLineEdit(LoginWindow)
        self.code_line.setGeometry(QtCore.QRect(120, 70, 221, 31))
        self.code_line.setText("")
        self.code_line.setObjectName("code_line")
        self.name_line = QtWidgets.QLineEdit(LoginWindow)
        self.name_line.setGeometry(QtCore.QRect(120, 30, 221, 31))
        self.name_line.setObjectName("name_line")
        self.label_3 = QtWidgets.QLabel(LoginWindow)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 91, 41))
        self.label_3.setObjectName("label_3")
        self.time_label = QtWidgets.QLabel(LoginWindow)
        self.time_label.setGeometry(QtCore.QRect(120, 160, 221, 41))
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.sampInfo_label = QtWidgets.QLabel(LoginWindow)
        self.sampInfo_label.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.sampInfo_label.setObjectName("sampInfo_label")
        self.sampInfo_line = QtWidgets.QLineEdit(LoginWindow)
        self.sampInfo_line.setGeometry(QtCore.QRect(120, 110, 221, 31))
        self.sampInfo_line.setObjectName("sampInfo_line")
        self.confirm_butt = QtWidgets.QPushButton(LoginWindow)
        self.confirm_butt.setGeometry(QtCore.QRect(100, 230, 141, 51))
        self.confirm_butt.setObjectName("confirm_butt")

        self.retranslateUi(LoginWindow)
        self.confirm_butt.clicked.connect(LoginWindow.confirm)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Dialog"))
        self.name_label.setText(_translate("LoginWindow", "操作人姓名："))
        self.code_label.setText(_translate("LoginWindow", "操作人编号："))
        self.label_3.setText(_translate("LoginWindow", "操作时间："))
        self.sampInfo_label.setText(_translate("LoginWindow", "待测品信息："))
        self.confirm_butt.setText(_translate("LoginWindow", "确定"))
